experiment:
  name: "EMD_gaussian_target"
parameters:
  polar_transform: True
  subsampling_factor: 10
  use_neighbor_diff: True
  epochs: 5
  batch_size: 16
  lr: 0.001
  model_name: "WeakCMEUNet"
  model_params:
    in_channels: 5
  loss_name: "CMELossAngularProfileWasserstein"
  loss_params:
    gaussian_target: True
    sigma_target: 10.0
